### ISSUE TITLE
create admin util to manage users (create, update/reset pw/api keys, delete), `replayd`: maybe called `replaydctl`

### ISSUE THREAD

**Issue by wwlwpd** [StormSurgeLive/StormReplay.com#14]
Part 1:
- [x] user DB init script
- [x] `add user` script that uses a library defining members
- [x] web app to use SQLite DB instead of YAML
- [x] API to use SQLite DB instread of YAML

Part 2:
- [x] CLI account create tool that emails credentials to provided email address (used for "invite" mode)
- [ ] #21

Part 3:
- [ ] #22
